config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'user/registrations',
    omniauth_callbacks: 'user/omniauth_callbacks'
  }

  resource :account,   only: %i[show update]
  resource :wizards,   only: %i[show update]

  resources :deals,    only: %i[index show new create edit update]
  resources :requests, only: %i[index new create edit update] do
    get :add
  end
  resources :explores, only: %i[index]

  resources :categories, only: %i[index] do
    resources :deals, only: %i[index]
    resources :requests, only: %i[index]
    resources :explores, only: %i[index]

    resources :subcategories, only: [] do
      resources :deals, only: %i[index]
      resources :requests, only: %i[index]
      resources :explores, only: %i[index]
    end
  end

  resources :products, path: 'p', only: %i[show new create] do
    get :deal, on: :member
    collection do
      post :fetch
      get :existing
      get :search
    end
  end

  resources :transactions, only: %i[index] do
    get :returns, on: :collection
    get :payments, on: :collection
  end
  resources :carts, only: %i[index]
  resources :orders, only: %i[index show]

  get 'terms', to: 'static#terms'
  get 'privacy', to: 'static#privacy'

  # Root to deals page
  root to: 'deals#index'
  get 'localedata/get_zip_data/:code', :controller => 'mycontrollername', :action => 'get_zip_data'

end

app/models/product.rb
class Product < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user
  belongs_to :category
  belongs_to :sub_category, class_name: 'Category'

  has_many :product_images
  has_many :requests
  has_many :deals, inverse_of: :product

  friendly_id :title, use: :slugged

  accepts_nested_attributes_for :product_images, allow_destroy: true

  validates :unit, presence: true
  validates :title, presence: true
  validates :standard_price, presence: true

  ##
  # this writer and reader method are for converting standard price to cents
  def price_amount=(new_price = 0)
    self.standard_price = new_price.to_f * 100
  end

  def price_amount
    if standard_price
      standard_price / 100.0
    else
      0
    end
  end

  ##
  # TODO: needed to be redeveloped to select many products
  def self.most_used(current_user, priority_product_id)
    limit(5).order("position(id::text in '#{priority_product_id}') DESC")
  end

  def primary_image
    product_images.first&.image
  end

  def fetch_from_url
    Logical::ProductScrapper.new(product_url, self).product
  end
end

# == Schema Information
#
# Table name: products
#
#  id              :integer          not null, primary key
#  user_id         :integer
#  title           :string
#  description     :text
#  standard_price  :integer
#  quantity        :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  category_id     :integer
#  sub_category_id :integer
#  product_url     :string
#  unit            :string
#  slug            :string
#

app/controllers/products_controller.rb
# frozen_string_literal: true

#
class ProductsController < ApplicationController
  def show
    @product = Product.friendly.find(params[:id])
  end

  def new
    @product = Product.new
  end

  # scraping the meta tag
  def fetch
    @product = Product.new(
      params
        .require(:product)
        .permit(:category_id, :sub_category_id, :product_url)
    ).fetch_from_url
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to existing_products_path(product: @product.slug)
    else
      render :new
    end
  end

  def search
    keyword = params[:keyword].strip
    @products = Product.where('title LIKE :keyword OR description LIKE :keyword', keyword: "%#{keyword}%")
    @products = @products.where(sub_category_id: params[:sub_category_id]) if params[:sub_category_id].present?
  end

  def existing
    @product = Product.friendly.find(params[:product])
    if @product.present?
      @products = Product.where(sub_category_id: @product.sub_category_id).order('created_at DESC');
      @deal = Deal.new
      @deal.product_deals.build
    end
  end

  def deal
  
  end  

  private

  def product_params
    params.require(:product).permit(
      :product_url, :title, :category_id, :sub_category_id,
      :price_amount, :unit, :description,
      product_images_attributes: %i[img image_url]
    )
  end
end

app/views/products/new/_modal_form.html.haml
.reveal.discounts_popup.add_por_inner#product_pop_add_inner{ data: { reveal: true } }
  %h3 Edit my product details
  %hr
  = simple_form_for product, wrapper: 'product_form', html: { id: 'product-form', multipart: true } do |f|
    = f.input :product_url, required: true
    = f.input :title, label: 'Product Name', required: true
    = f.input :category_id, collection: Category.parents_only.map { |c| [c.name, c.id] }, include_blank: false, label: 'Product Category', required: true, input_html: { data: { action: 'select-category', category_url: categories_path(format: :json) } }
    = f.input :sub_category_id, collection: [], include_blank: false, label: 'Product Subcategory', required: true, input_html: { data: { action: 'select-subcategory'} }
    = f.input :price_amount, as: :numeric, label: 'Standard Price', required: true, input_html: { step: '0.01' }
    = f.input :unit, required: true, collection: Enum::Product::Units[:options]
    .row
      .small-4.columns
        %label.text-right{ for: 'right-label' } Product Picture
      .small-8.columns
        = f.fields_for :product_images do |pi|
          %label.button.upload_btn
            = image_tag pi.object.image, alt: 'Attach', style: 'width: 82px;'
            = pi.file_field :img, class: 'show-for-sr', data: { action: 'select-product-image' }
            = pi.hidden_field :image_url

    = f.input :description
    .error-wrapper
      - if product.errors.present?
        %p.help-text{ style: 'color: red;'}
          = product.errors.full_messages.join(', ')
    
    %hr
    .submit-data
      %button.button.sikp_btn{ type: 'button', data: { close: '' }, aria: { label: 'Close reveal'} } CANCEL
      = f.submit 'CONTINUE', class: 'button add_btn', id: 'product_create'
    %button.close-button{ type: 'button', data: { close: 'true' }, aria: { label: 'Close reveal'} }

  

app/views/products/new/_modal_product_url.html.haml
#product_pop_add.reveal.discounts_popup.products_add_popup{ data: { reveal: true } }
  %h3 Add product details
  %hr
  = form_for product, url: fetch_products_path, remote: true, html: { class: 'input-product-url' }  do |f|
    = f.hidden_field :category_id, data: { target: 'product-category' }
    = f.hidden_field :sub_category_id, data: { target: 'product-subcategory' }
    %p
      Please
      = link_to 'read', 'javascript:void()'
      our guidelines before adding an product.
      %h3 Product URL
      = f.text_field :product_url, placeholder: 'http://www.productpage.com'
      .error-wrapper
      .Modal_footer
        = f.submit 'CONTINUE', class: 'button pop_up_btn'
      %button.close-button{ data: { close: true }, aria: { label: 'Close reveal' }, type: 'button' }
        %span{ aria: { hidden: true } } &times;