config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'user/registrations',
    omniauth_callbacks: 'user/omniauth_callbacks'
  }

  resource :account,   only: %i[show update]
  resource :wizards,   only: %i[show update]

  resources :deals,    only: %i[index show new create edit update]
  resources :requests, only: %i[index new create edit update] do
    get :add
  end
  resources :explores, only: %i[index]

  resources :categories, only: %i[index] do
    resources :deals, only: %i[index]
    resources :requests, only: %i[index]
    resources :explores, only: %i[index]

    resources :subcategories, only: [] do
      resources :deals, only: %i[index]
      resources :requests, only: %i[index]
      resources :explores, only: %i[index]
    end
  end

  resources :products, path: 'p', only: %i[show new create] do
    get :deal, on: :member
    collection do
      post :fetch
      get :existing
      get :search
    end
  end

  resources :transactions, only: %i[index] do
    get :returns, on: :collection
    get :payments, on: :collection
  end
  resources :carts, only: %i[index]
  resources :orders, only: %i[index show]

  get 'terms', to: 'static#terms'
  get 'privacy', to: 'static#privacy'

  # Root to deals page
  root to: 'deals#index'
  get 'localedata/get_zip_data/:code', :controller => 'mycontrollername', :action => 'get_zip_data'

end

app/views/shared/_authorized_header.html.erb
<%= render 'shared/categories_nav' %>
<%= render 'shared/cart' %>

<div class="top_header">

  <div class="top_header_inner">
    <!-- Left side bar menu Icon -->
    <div class="side_bar_menu_icon">
      <div class="navTrigger">
        <i></i><i></i><i></i>
      </div>

      <div class="search_bar">
        <div class="search">
          <i class="fa fa-search"></i>
          <input placeholder="Search deals" type="search" name="search">
        </div>
      </div>
    </div>
    <!-- Center Logo -->
    <div class="center_logo">
      <%= link_to root_path do %>
        <%= image_tag 'logo.png' %>
      <% end %>
    </div>
    <!-- Header Right -->
    <div class="right_head">
      <!-- User info -->
      <div class="account_info">
        <div class="user_pic">
          <%= image_tag current_user.profile.avatar.url, style: 'width: 35px; height: 35px;' %>
        </div>

        <div class="customer">

          <ul class="dropdown menu" data-dropdown-menu>
            <li>
              <a href="#">Account</a>
              <ul class="menu no-bullet">
                <li><%= link_to 'My Deals', deal_path('active') %></li>
                <li><%= link_to 'My Discounts', deal_path('item') %></li>
                <li><%= link_to 'Transactions', transactions_path %></li>
                <li><%= link_to 'Returns', returns_transactions_path %></li>
                <li><%= link_to 'Payments', payments_transactions_path %></li>
                <li><%= link_to 'Order History', order_path('history') %></li>
                <li><%= link_to 'Account Settings', account_path %></li>
                <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
      <!-- Cart Icon -->
      <div class="cart_icon">
        <div class="top-bar-right"> <span id="cartImage" class="cart-item">0</span> </div>
      </div>
    </div>
  </div>
  <%- unless (controller_name == 'products' && (['show', 'deal'].include?(action_name))) ||
              (['carts', 'orders', 'static'].include?(controller_name)) ||
              (controller_name == 'transactions' && action_name == 'index') %>
    <div class="center_menu">
      <ul>
        <li class="<%= 'active_menu' if controller_name == 'deals' %>"><a href="<%= specific_deals_url %>" >DEALS</a></li>
        <li class="<%= 'active_menu' if controller_name == 'explores' %>"><a href="<%= specific_explores_url %>">EXPLORE</a></li>
        <li class="<%= 'active_menu' if controller_name == 'requests' %>"><a href="<%= specific_requests_url %>">REQUESTS</a></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/shared/_business_form.html.erb
<%= render 'shared/user_business_form', f: f, p: p %>
<div class="columns">
  <label>
    <%= p.label :authorized_product %>
    <%= p.select :authorized_product, Enum::Profile::SomeProduct[:options] %>
  </label>
</div>
<div class="columns">
  <label>
    <%= p.label :anual_online_revenue %>
    <%= p.select :anual_online_revenue, Enum::Profile::Revenue[:options] %>
  </label>
</div>
<div class="columns">
  <label>
    <%= p.label :sku_in_catalog %>
    <%= p.select :sku_in_catalog, Enum::Profile::SKU[:options] %>
  </label>
</div>
<div class="columns">
  <label>
    <%= p.label :top_selling_brand %>
    <%= p.text_field :top_selling_brand %>
  </label>
</div>
<div class="columns">
  <label>
    <%= p.label :sell_used_product %>
    <%= p.select :sell_used_product, Enum::Profile::SomeProduct[:options] %>
  </label>
</div>
<div class='columns'>
  <label>
    <%= p.label :map_rpm_policies %>
    <%= p.select :map_rpm_policies, Enum::Profile::MapPolicies[:options] %>
  </label>
</div>
<div class='columns'>
  <label>
    <%= p.label :walmart_supplier %>
    <%= p.select :walmart_supplier, Enum::Profile::SellOnWallmart[:options] %>
  </label>
</div>
<div class='columns'>
  <label>
    <%= p.label :ecommerce_url %>
    <%= p.text_field :ecommerce_url %>
  </label>
</div>
<div class='columns'>
  <label>
    <%= p.label :marketplace_provider %>
    <%= p.select :marketplace_provider, Enum::Profile::OnlineStores[:options] %>
  </label>
</div>
<div class='columns'>
  <label>
    <%= p.label :marketplace_url %>
    <%= p.text_field :marketplace_url %>
  </label>
</div>
<div class='columns'>
  <label>
    <%= p.label :integration %>
    <%= p.select :integration, Enum::Profile::Integration[:options] %>
  </label>
</div>
<div class='columns'>
  <label>
    <%= p.label :inventory_update %>
    <%= p.select :inventory_update, Enum::Profile::UpdateFrequency[:options] %>
  </label>
</div>
<div class='columns'>
  <label>
    <%= p.label :average_ships %>
    <%= p.select :average_ships, Enum::Profile::OrderFrequency[:options] %>
  </label>
</div>
<div class='columns'>
  <label>
    <%= p.label :own_inventory %>
    <%= p.select :own_inventory, { 'Yes' => true, 'No' => false } %>
  </label>
</div>
<div class='columns'>
  <label>
    <%= p.label :fulfillment %>
    <%= p.text_field :fulfillment %>
  </label>
</div>
<div class='columns'>
  <label>
    <%= p.label :dropshipper %>
    <%= p.number_field :dropshipper, min: 1 %>
  </label>
</div>
<div class='columns'>
  <label>
    <%= p.label :order_to_shiptime %>
    <%= p.select :order_to_shiptime, Enum::Profile::ShipTime[:options] %>
  </label>
</div>
<div class='columns'>
  <label>
    <%= p.label :shiptime_guarantee %>
    <%= p.select :shiptime_guarantee, Enum::Profile::ShipTimeGuarantee[:options] %>
  </label>
</div>
<div class='columns'>
  <label>
    <%= p.label :freight_carrier %>
    <%= p.select :freight_carrier, Enum::Profile::Sometimes[:options] %>
  </label>
</div>
<div class='columns'>
  <label>
    <%= p.label :return_policy %>
    <%= p.select :return_policy, Enum::Profile::ReturnPolicy[:options] %>
  </label>
</div>
<div class='columns'>
  <%= p.label :carriers_name %>
  <% Enum::Profile::Carriers[:options].each do |carrier| %>
    <label>
      <%= p.check_box :carriers_name, {multiple: true}, carrier %>
      <%= carrier %>
    </label>
  <% end %>
</div>
<div class='columns'>
  <%= p.label :physical_store %>
  <label class='pull-left'>
    <%= p.radio_button :physical_store, true %>
    Yes
  </label>
  <label class='pull-left'>
    <%= p.radio_button :physical_store, false %>
    No
  </label>
</div>
<div class='columns hide physical-store-related'>
  <%= p.label :fulfill_from_store %>
  <label class='pull-left'>
    <%= p.radio_button :fulfill_from_store, true %>
    Yes
  </label>
  <label class='pull-left'>
    <%= p.radio_button :fulfill_from_store, false %>
    No
  </label>
</div>
<div class='columns hide physical-store-related'>
  <%= p.label :store_pickup %>
  <label class='pull-left'>
    <%= p.radio_button :store_pickup, true %>
    Yes
  </label>
  <label class='pull-left'>
    <%= p.radio_button :store_pickup, false %>
    No
  </label>
</div>

app/views/shared/_cart.html.erb
<div class="cart_side_right">
  <div class="cart_delivery">
    <h3>Your Request</h3>

    <div class="delivery_form">

      <input  placeholder="Delivery Date..." class="span2" id="dp1" type="text">
      <button class="button enter" onclick="location.href='<%= carts_path %>';">CONTINUE</button>
    </div>


    <div class="cart_item" id="style-1">
      <div class="item-list">
        <span class="item">
          <strong class="name">KOBE XI<span>Men's Basketball Shoe</span></strong>
          <span class="price">$160</span>
          <button class="remove"><i class="fa fa-times" aria-hidden="true"></i></button>
        </span>

        <span class="item">
          <strong class="name">KOBE XI<span>Men's Basketball Shoe</span></strong>
          <span class="price">$160</span>
          <button class="remove"><i class="fa fa-times" aria-hidden="true"></i></button>
        </span>

        <span class="item">
          <strong class="name">KOBE XI<span>Men's Basketball Shoe</span></strong>
          <span class="price">$160</span>
          <button class="remove"><i class="fa fa-times" aria-hidden="true"></i></button>
        </span>
        <span class="item">
          <strong class="name">KOBE XI<span>Men's Basketball Shoe</span></strong>
          <span class="price">$160</span>
          <button class="remove"><i class="fa fa-times" aria-hidden="true"></i></button>
        </span>

        <span class="item">
          <strong class="name">KOBE XI<span>Men's Basketball Shoe</span></strong>
          <span class="price">$160</span>
          <button class="remove"><i class="fa fa-times" aria-hidden="true"></i></button>
        </span>

        <span class="item">
          <strong class="name">KOBE XI<span>Men's Basketball Shoe</span></strong>
          <span class="price">$160</span>
          <button class="remove"><i class="fa fa-times" aria-hidden="true"></i></button>
        </span>

        <span class="item">
          <strong class="name">KOBE XI<span>Men's Basketball Shoe</span></strong>
          <span class="price">$160</span>
          <button class="remove"><i class="fa fa-times" aria-hidden="true"></i></button>
        </span>

        <span class="item">
          <strong class="name">KOBE XI<span>Men's Basketball Shoe</span></strong>
          <span class="price">$160</span>
          <button class="remove"><i class="fa fa-times" aria-hidden="true"></i></button>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/shared/_categories_nav.html.erb
<div class="sidenav">
  <aside>
    <h3 class="side_bar_title">YOVA Wholesale Shop</h3>
    <ul class="vertical menu drilldown" data-drilldown>
      <% Category.parents_only.each do |category| %>
        <li>
          <%= link_to category.name, '#' %>
          <ul class='menu vertical nested'>
            <h3><%= category.name %></h3>
            <li><%= link_to "See all #{category.name}", category_deals_path(category), class: 'see_all_active' %></li>
            <% category.childrens.each do |child| %>
              <li>
                <%= link_to child.name, category_subcategory_deals_path(category, child) %>
              </li>
            <% end %>
          </ul>
        </li>
      <% end %>
      <li><a href="#">Best Sellers</a></li>
    </ul>
  </aside>
</div>

app/views/shared/_error_message.html.erb
<%- if object.errors.length > 0 %>
  <div class='callout alert'>
    <ul>
      <% object.errors.each do |attr,msg| %>
        <li><%= msg.humanize %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="top-bar top_bar_flex">
  <div class="top-bar-title">
    <%= link_to root_path do %>
      <%= image_tag 'logo.png' %>
    <% end %>
  </div>
  <div class="top-bar-right">
    <%= link_to 'Sign Up', new_user_registration_path, class: 'button login' %>
    <%= link_to 'Sign In', new_user_session_path, class: 'button login' %>
  </div>
</nav>

app/views/shared/_user_business_form.html.erb
<div class="columns text-center">
  <%= image_tag p.object.avatar.url, class: 'thumbnail', id: 'avatar-image' %>
  <div class="upload float-center">
    <%= p.label :avatar %>
    <%= p.file_field :avatar, class: 'show-for-sr' %>
  </div>
</div>
<div class="columns">
  <%- if current_user.errors.full_messages.length > 0 %>
    <div class='callout alert'>
      All field is required
    </div>
  <% end %>
  <label>Legal Business Name
    <%= p.text_field :biz_name %>
	</label>
</div>
<div class="columns">
  <label>Industry
    <%= p.select :industry, ['Industry1', 'Industry2', 'Industry3'] %>
	</label>
</div>
<div class="columns">
  <label>Business Address
    <%= p.text_field :biz_address %>
	</label>
</div>
<div class="columns">
  <label>Tax ID
    <%= p.text_field :tax_id, placeholder: '12-3456789' %>
	</label>
</div>
<div class="columns small-6 zipcode_interactive">
  <label>Zip
    <%= p.text_field :zip, :class => 'zipcode_interactive' %>
	</label>
</div>
<div class="columns">
  <label>City
    <%= p.text_field :city %>
	</label>
</div>
<div class="columns small-6">
  <label>State
    <%= p.select :state, options_for_select(us_states, p.object.state) %>
	</label>
</div>

app/views/shared/_wizard_header.html.erb
<div class="top-bar top-bar_flex">
  <!-- Center Logo -->
  <div class="center_logo single_flex">
    <%= link_to destroy_user_session_path, method: :delete do %>
      <%= image_tag 'logo.png' %>
    <% end %>
  </div>

  <div class="top-bar-center  single_flex">
    <div class="button-group"> 
      <% step = params[:step] ? params[:step].to_i : current_user.reload.profile.current_step_index %>
      <a href='<%= wizards_path(step: 0) %>' class="button <%= step >= 0 ? 'active' : 'disabled wizard-link' %>">CHOOSE PROFILE</a> 
      <a href='<%= wizards_path(step: 1) %>' class="button <%= step >= 1 ? 'active' : 'disabled wizard-link' %>">SELECT CATEGORIES</a> 
      <a href='<%= wizards_path(step: 4) %>' class="button <%= step >= 4 ? 'active' : 'disabled wizard-link' %>">REGISTER</a> 
      <a href='<%= wizards_path(step: 5) %>' class="button <%= step >= 5 ? 'active' : 'disabled wizard-link' %>">COMPLETE</a> 
    </div>
  </div>

  <div class="home_right_acc_info  single_flex sing_icon_width">
    <div class="top-bar-right">
      <%= link_to 'Sign In', destroy_user_session_path, method: :delete, class: 'button login' %>
    </div>
  </div> 
</div>