config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'user/registrations',
    omniauth_callbacks: 'user/omniauth_callbacks'
  }

  resource :account,   only: %i[show update]
  resource :wizards,   only: %i[show update]

  resources :deals,    only: %i[index show new create edit update]
  resources :requests, only: %i[index new create edit update] do
    get :add
  end
  resources :explores, only: %i[index]

  resources :categories, only: %i[index] do
    resources :deals, only: %i[index]
    resources :requests, only: %i[index]
    resources :explores, only: %i[index]

    resources :subcategories, only: [] do
      resources :deals, only: %i[index]
      resources :requests, only: %i[index]
      resources :explores, only: %i[index]
    end
  end

  resources :products, path: 'p', only: %i[show new create] do
    get :deal, on: :member
    collection do
      post :fetch
      get :existing
      get :search
    end
  end

  resources :transactions, only: %i[index] do
    get :returns, on: :collection
    get :payments, on: :collection
  end
  resources :carts, only: %i[index]
  resources :orders, only: %i[index show]

  get 'terms', to: 'static#terms'
  get 'privacy', to: 'static#privacy'

  # Root to deals page
  root to: 'deals#index'
  get 'localedata/get_zip_data/:code', :controller => 'mycontrollername', :action => 'get_zip_data'

end

app/models/deal.rb
# == Schema Information
#
# Table name: deals
#
#  id                 :integer          not null, primary key
#  promotion_days     :integer          not null
#  number_of_commits  :integer          not null
#  promotion_start_at :date             not null
#  number_of_quantity :integer          not null
#  status             :integer          not null
#  description        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  request_id         :integer
#  user_id            :integer
#

class Deal < ActiveRecord::Base
  enum status: [:active, :inactive]

  belongs_to :user, inverse_of: :deals
  has_many :product_deals, dependent: :destroy
  has_many :products, through: :product_deals
  
  accepts_nested_attributes_for :product_deals, allow_destroy: true

  validates :user_id, :status, presence: true
  # validates :promotion_days, :number_of_commits, :number_of_quantity, presence: true, numericality: true
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :authenticate_user!

  def index
    @deals = ProductDeal.joins([:deal, :product]).includes([:deal, :product]).order(:created_at)
    @deals = @deals.where(status: Deal.statuses[:active])
    @deals = @deals.where('deals.expired_at >= ?', Date.today)
    @deals = @deals.paginate(page: params[:page], per_page: 12)
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
  	@product = Product.find_by(slug: params[:product]) if params[:product].present? 
  end

  def create
  	params[:deal] = {} if params[:deal].blank?
    product_ids = params[:product_ids]

    if product_ids.present?
      params[:deal][:product_deals_attributes] = {}
      product_ids.each_with_index do |product_id, index|
        params[:deal][:product_deals_attributes]["#{index}"] = { product_id: product_id }
      end  
    end

    @deal = Deal.new(deal_params)
    @deal.user = current_user
    @deal.status = Deal.statuses[:inactive]
    @deal.promotion_start_at = Date.today
    @deal.save
  end

  def update
    @deal = Deal.find(params[:id])
    promotion_days = params[:deal][:promotion_days]
    
    if params[:deal][:status].blank? && @deal.inactive?
      @deal.status = Deal.statuses[:active]
    end

    #@deal.expired_at = @deal.promotion_start_at + promotion_days.to_i.days if promotion_days.present?
    @deal.expired_at = @deal.promotion_start_at + promotion_days.to_i.days
    @deal.update_attributes(deal_params)  
  end  

  ##
  # deals/active
  def show
    @page = params[:id] || 'active'
  end

  private

  def deal_params
    params.require(:deal).permit(
      :promotion_days, :number_of_commits, :number_of_quantity,
      product_deals_attributes: %i[product_id]
    )
  end
end

app/views/deals/_category.html.erb
<%= title 'Account - Your Discount' %>
<section class="main-section mar_top_d">
  <div class="row expanded " id="sticker">
    <div class="columns deals-filter">
      <div class="row expanded">
        <div class="columns small-6">
          <a href="<%= deal_path('item') %>" class="button">Product Discounts</a>
          <a class="button active">Product Category Discounts</a>
        </div>
      </div>
    </div>
    <div class="main_product_area mar_remove">
      <div class="row category_filter">
        <div class="border_bottom small-12 large-12 medium-12 columns" id="sticker">
          <div class="border_bottom_p">
            <div class="single_fliter width_one">
              <p>Filter by:</p>
              <div class="Filter_drop_down">
                <ul class="nav">
                  <li class="button-dropdown">
                    <a href="javascript:void(0)" class="dropdown-toggle">
                               Categories <span><i class="fa fa-angle-down" aria-hidden="true"></i></span>
                              </a>
                    <ul class="dropdown-menu max_height">
                      <li>
                        <a href="#">
                          <div class="dot active_dot"></div>Grocery</a>
                        <div class="sub_drop_menu">
                          <ul>
                            <li>
                              <a href="#">
                                <div class="dot active_dot"></div>Grocery 1</a>
                            </li>
                            <li>
                              <a href="#">
                                <div class="dot"></div>Grocery 2</a>
                            </li>
                            <li>
                              <a href="#">
                                <div class="dot"></div>Grocery 3</a>
                            </li>
                            <li>
                              <a href="#">
                                <div class="dot"></div>Grocery 4</a>
                            </li>
                          </ul>
                        </div>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Household Products</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Health & Wellness</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Beauty & Personal Care</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Baby</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Pet Supplies</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Electronics</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div>Office Products</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Tools & Hardware</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Business Essentials</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Best Sellers</a>
                      </li>

                    </ul>
                  </li>
                </ul>
              </div>

              <div class="Filter_drop_down">
                <ul class="nav">
                  <li class="button-dropdown">
                    <a href="javascript:void(0)" class="dropdown-toggle">
                                Brands <span><i class="fa fa-angle-down" aria-hidden="true"></i></span>
                              </a>
                    <ul class="dropdown-menu max_height">
                      <li>
                        <div class="input-group dropdown_search">
                          <span class="input-group-label"><i class="fa fa-search"></i></span>
                          <input class="input-group-field" type="search">
                        </div>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot active_dot"></div> Grocery</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Household Products</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Health & Wellness</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Beauty & Personal Care</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Baby</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Pet Supplies</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Electronics</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div>Office Products</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Tools & Hardware</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Business Essentials</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Best Sellers</a>
                      </li>

                    </ul>
                  </li>
                </ul>
              </div>


              <div class="Filter_drop_down">
                <ul class="nav">
                  <li class="button-dropdown">
                    <a href="javascript:void(0)" class="dropdown-toggle">
                                Prices <span><i class="fa fa-angle-down" aria-hidden="true"></i></span>
                              </a>
                    <ul class="dropdown-menu max_height">
                      <li>
                        <a href="#">
                          <div class="dot active_dot"></div> $0-25 <span>(240)</span></a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div>$25-50 <span>(24)</span></a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> $50-100 <span>(40)</span></a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> $100-200 <span>(23)</span></a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> $200 and Above <span>(50)</span></a>
                      </li>
                      <li class="price_search_drop">
                        <div class="hulf_search_price">
                          <span>$</span> <input type="text">
                        </div>
                        <div class="hulf_search_price">
                          <span>$</span> <input type="text">
                        </div>
                        <div class="hulf_search_price">
                          <p class="go_link">go</p>
                        </div>
                      </li>

                    </ul>
                  </li>
                </ul>
              </div>


              <div class="Filter_drop_down">
                <ul class="nav">
                  <li class="button-dropdown">
                    <a href="javascript:void(0)" class="dropdown-toggle">
                                Refine By Type <span><i class="fa fa-angle-down" aria-hidden="true"></i></span>
                              </a>
                    <ul class="dropdown-menu max_height">
                      <li>
                        <a href="#">
                          <div class="dot active_dot"></div> Grocery</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Household Products</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Health & Wellness</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Beauty & Personal Care</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Baby</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Pet Supplies</a>
                      </li>


                    </ul>
                  </li>
                </ul>
              </div>
            </div>

            <div class="single_fliter width_two">
              <p>Sort by:</p>
              <div class="Filter_drop_down">
                <ul class="nav">
                  <li class="button-dropdown">
                    <a href="javascript:void(0)" class="dropdown-toggle">
                               Relevance <span><i class="fa fa-angle-down" aria-hidden="true"></i></span>
                              </a>
                    <ul class="dropdown-menu max_height">
                      <li>
                        <a href="#">
                          <div class="dot active_dot"></div> Relevance</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Price Low to High</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> price high to Low</a>
                      </li>
                    </ul>
                  </li>
                </ul>
              </div>

            </div>


            <div class="single_fliter width_five">
              <div class="new_deal">
                <ul class="dropdown menu" data-dropdown-menu>
                  <li>
                    <a href="#">NEW DEAL</a>
                    <ul class="menu no-bullet">
                      <li><a href="<%= existing_products_path %>">Existing Product</a></li>
                      <li><a href="<%= new_product_path %>">New Product</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>


          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row expanded">
    <div class="columns table item-table">
      <table class="stack">
        <thead>
          <tr>
            <td>PRODUCTS</td>
            <td>STANDARD PRICE</td>
            <td>DISCOUNT TYPE</td>
            <td>QUANTITY</td>
            <td>DISCOUNT AMOUNT</td>
            <td>DISCOUNT PRICE</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= image_tag 'shoe.jpg' %> Grocery</td>
            <td>180</td>
            <td>Dollar Amount</td>
            <td>10 - 30 boxes</td>
            <td>$30</td>
            <td>150</td>
          </tr>
          <tr>
            <td><%= image_tag 'shoe.jpg' %> Beauty & Apparel</td>
            <td>180</td>
            <td>Dollar Amount</td>
            <td>10 - 30 boxes</td>
            <td>$30</td>
            <td>150</td>
          </tr>
          <tr>
            <td><%= image_tag 'shoe.jpg' %> Baby</td>
            <td>180</td>
            <td>Dollar Amount</td>
            <td>10 - 30 boxes</td>
            <td>$30</td>
            <td>150</td>
          </tr>
          <tr>
            <td><%= image_tag 'shoe.jpg' %> Business Essentials</td>
            <td>180</td>
            <td>Dollar Amount</td>
            <td>10 - 30 boxes</td>
            <td>$30</td>
            <td>150</td>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</section>

<%= render 'shared/modal/assign_discount_by_product' %>

app/views/deals/_item.html.erb
<%= title 'Account - Your Discount' %>
<section class="main-section mar_top_d">
  <div class="row expanded " id="sticker">
    <div class="columns deals-filter">
      <div class="row expanded">
        <div class="columns small-6">
          <a class="button active">Product Discounts</a>
          <a href="<%= deal_path('category') %>" class="button">Product Category Discounts</a>
        </div>
      </div>
    </div>
    <div class="main_product_area mar_remove">
      <div class="row category_filter">
        <div class="border_bottom small-12 large-12 medium-12 columns" id="sticker">
          <div class="border_bottom_p">
            <div class="single_fliter width_one">
              <p>Filter by:</p>
              <div class="Filter_drop_down">
                <ul class="nav">
                  <li class="button-dropdown">
                    <a href="javascript:void(0)" class="dropdown-toggle">
                               Categories <span><i class="fa fa-angle-down" aria-hidden="true"></i></span>
                              </a>
                    <ul class="dropdown-menu max_height">
                      <li>
                        <a href="#">
                          <div class="dot active_dot"></div>Grocery</a>
                        <div class="sub_drop_menu">
                          <ul>
                            <li>
                              <a href="#">
                                <div class="dot active_dot"></div>Grocery 1</a>
                            </li>
                            <li>
                              <a href="#">
                                <div class="dot"></div>Grocery 2</a>
                            </li>
                            <li>
                              <a href="#">
                                <div class="dot"></div>Grocery 3</a>
                            </li>
                            <li>
                              <a href="#">
                                <div class="dot"></div>Grocery 4</a>
                            </li>
                          </ul>
                        </div>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Household Products</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Health & Wellness</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Beauty & Personal Care</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Baby</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Pet Supplies</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Electronics</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div>Office Products</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Tools & Hardware</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Business Essentials</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Best Sellers</a>
                      </li>

                    </ul>
                  </li>
                </ul>
              </div>

              <div class="Filter_drop_down">
                <ul class="nav">
                  <li class="button-dropdown">
                    <a href="javascript:void(0)" class="dropdown-toggle">
                                Brands <span><i class="fa fa-angle-down" aria-hidden="true"></i></span>
                              </a>
                    <ul class="dropdown-menu max_height">
                      <li>
                        <div class="input-group dropdown_search">
                          <span class="input-group-label"><i class="fa fa-search"></i></span>
                          <input class="input-group-field" type="search">
                        </div>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot active_dot"></div> Grocery</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Household Products</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Health & Wellness</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Beauty & Personal Care</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Baby</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Pet Supplies</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Electronics</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div>Office Products</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Tools & Hardware</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Business Essentials</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Best Sellers</a>
                      </li>

                    </ul>
                  </li>
                </ul>
              </div>


              <div class="Filter_drop_down">
                <ul class="nav">
                  <li class="button-dropdown">
                    <a href="javascript:void(0)" class="dropdown-toggle">
                                Prices <span><i class="fa fa-angle-down" aria-hidden="true"></i></span>
                              </a>
                    <ul class="dropdown-menu max_height">
                      <li>
                        <a href="#">
                          <div class="dot active_dot"></div> $0-25 <span>(240)</span></a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div>$25-50 <span>(24)</span></a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> $50-100 <span>(40)</span></a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> $100-200 <span>(23)</span></a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> $200 and Above <span>(50)</span></a>
                      </li>
                      <li class="price_search_drop">
                        <div class="hulf_search_price">
                          <span>$</span> <input type="text">
                        </div>
                        <div class="hulf_search_price">
                          <span>$</span> <input type="text">
                        </div>
                        <div class="hulf_search_price">
                          <p class="go_link">go</p>
                        </div>
                      </li>

                    </ul>
                  </li>
                </ul>
              </div>


              <div class="Filter_drop_down">
                <ul class="nav">
                  <li class="button-dropdown">
                    <a href="javascript:void(0)" class="dropdown-toggle">
                                Refine By Type <span><i class="fa fa-angle-down" aria-hidden="true"></i></span>
                              </a>
                    <ul class="dropdown-menu max_height">
                      <li>
                        <a href="#">
                          <div class="dot active_dot"></div> Grocery</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Household Products</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Health & Wellness</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Beauty & Personal Care</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Baby</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Pet Supplies</a>
                      </li>


                    </ul>
                  </li>
                </ul>
              </div>
            </div>

            <div class="single_fliter width_two">
              <p>Sort by:</p>
              <div class="Filter_drop_down">
                <ul class="nav">
                  <li class="button-dropdown">
                    <a href="javascript:void(0)" class="dropdown-toggle">
                               Relevance <span><i class="fa fa-angle-down" aria-hidden="true"></i></span>
                              </a>
                    <ul class="dropdown-menu max_height">
                      <li>
                        <a href="#">
                          <div class="dot active_dot"></div> Relevance</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> Price Low to High</a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="dot"></div> price high to Low</a>
                      </li>
                    </ul>
                  </li>
                </ul>
              </div>

            </div>


            <div class="single_fliter width_five">
              <div class="new_deal">
                <ul class="dropdown menu" data-dropdown-menu>
                  <li>
                    <a href="#">NEW DEAL</a>
                    <ul class="menu no-bullet">
                      <li><a href="<%= existing_products_path %>">Existing Product</a></li>
                      <li><a href="<%= new_product_path %>">New Product</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>


          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row expanded">
    <div class="columns table item-table">
      <table class="stack">
        <thead>
          <tr>
            <td>PRODUCTS</td>
            <td>STANDARD PRICE</td>
            <td>DISCOUNT TYPE</td>
            <td>QUANTITY</td>
            <td>DISCOUNT AMOUNT</td>
            <td>DISCOUNT PRICE</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= image_tag 'shoe.jpg' %> Nike Shoes Extreme Run</td>
            <td>180</td>
            <td>Dollar Amount</td>
            <td>10 - 30 boxes</td>
            <td>$30</td>
            <td>150</td>
          </tr>
          <tr>
            <td><%= image_tag 'shoe.jpg' %> Nike Shoes Extreme Run</td>
            <td>180</td>
            <td>Dollar Amount</td>
            <td>10 - 30 boxes</td>
            <td>$30</td>
            <td>150</td>
          </tr>
          <tr>
            <td><%= image_tag 'shoe.jpg' %> Nike Shoes Extreme Run</td>
            <td>180</td>
            <td>Dollar Amount</td>
            <td>10 - 30 boxes</td>
            <td>$30</td>
            <td>150</td>
          </tr>
          <tr>
            <td><%= image_tag 'shoe.jpg' %> Nike Shoes Extreme Run</td>
            <td>180</td>
            <td>Dollar Amount</td>
            <td>10 - 30 boxes</td>
            <td>$30</td>
            <td>150</td>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</section>

<%= render 'shared/modal/assign_discount_by_product' %>

app/views/deals/index.html.erb
<%= title 'YOVA | DEALS' %>
<div class="main_product_area">
  <div class="row">
    <div class="columns medium-12 large-12 small-12">
      <div class="breadcom">
        <%= breadcrumbs %>
      </div>
    </div>
  </div>

  <div class="row category_filter">
    <div class="border_bottom small-12 large-12 medium-12 columns" id="sticker">
      <div class="border_bottom_p">
        <div class="single_fliter width_one">
          <p>Filter by:</p>
          <%= render "shared/filter/filter_by" %>
        </div>

        <div class="single_fliter width_two">
          <p>Sort by:</p>
          <%= render "shared/filter/sort_by" %>
        </div>

        <div class="single_fliter width_five">
          <div class="new_deal">
            <ul class="dropdown menu" data-dropdown-menu>
              <li>
                <a href="#" >NEW DEAL</a>
                <ul class="menu no-bullet">
                  <li><a href="<%= existing_products_path %>">Existing Product</a></li>
                  <li><a href="<%= new_product_path %>">New Product</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>

      </div>         
    </div>
  </div>
  <div class="row product_margin_top">
    <%= render 'products/deal_product', deal_products: @deals %>
  </div>
</div><!-- Tab End -->

</div>

<%= render 'shared/modal/popup_discount_table' %>

app/views/deals/show.html.erb
<%= render @page %>