config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'user/registrations',
    omniauth_callbacks: 'user/omniauth_callbacks'
  }

  resource :account,   only: %i[show update]
  resource :wizards,   only: %i[show update]

  resources :deals,    only: %i[index show new create edit update]
  resources :requests, only: %i[index new create edit update] do
    get :add
  end
  resources :explores, only: %i[index]

  resources :categories, only: %i[index] do
    resources :deals, only: %i[index]
    resources :requests, only: %i[index]
    resources :explores, only: %i[index]

    resources :subcategories, only: [] do
      resources :deals, only: %i[index]
      resources :requests, only: %i[index]
      resources :explores, only: %i[index]
    end
  end

  resources :products, path: 'p', only: %i[show new create] do
    get :deal, on: :member
    collection do
      post :fetch
      get :existing
      get :search
    end
  end

  resources :transactions, only: %i[index] do
    get :returns, on: :collection
    get :payments, on: :collection
  end
  resources :carts, only: %i[index]
  resources :orders, only: %i[index show]

  get 'terms', to: 'static#terms'
  get 'privacy', to: 'static#privacy'

  # Root to deals page
  root to: 'deals#index'
  get 'localedata/get_zip_data/:code', :controller => 'mycontrollername', :action => 'get_zip_data'

end

app/models/product.rb
class Product < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user
  belongs_to :category
  belongs_to :sub_category, class_name: 'Category'

  has_many :product_images
  has_many :requests
  has_many :deals, inverse_of: :product

  friendly_id :title, use: :slugged

  accepts_nested_attributes_for :product_images, allow_destroy: true

  validates :unit, presence: true
  validates :title, presence: true
  validates :standard_price, presence: true

  ##
  # this writer and reader method are for converting standard price to cents
  def price_amount=(new_price = 0)
    self.standard_price = new_price.to_f * 100
  end

  def price_amount
    if standard_price
      standard_price / 100.0
    else
      0
    end
  end

  ##
  # TODO: needed to be redeveloped to select many products
  def self.most_used(current_user, priority_product_id)
    limit(5).order("position(id::text in '#{priority_product_id}') DESC")
  end

  def primary_image
    product_images.first&.image
  end

  def fetch_from_url
    Logical::ProductScrapper.new(product_url, self).product
  end
end

# == Schema Information
#
# Table name: products
#
#  id              :integer          not null, primary key
#  user_id         :integer
#  title           :string
#  description     :text
#  standard_price  :integer
#  quantity        :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  category_id     :integer
#  sub_category_id :integer
#  product_url     :string
#  unit            :string
#  slug            :string
#

app/controllers/products_controller.rb
# frozen_string_literal: true

#
class ProductsController < ApplicationController
  def show
    @product = Product.friendly.find(params[:id])
  end

  def new
    @product = Product.new
  end

  # scraping the meta tag
  def fetch
    @product = Product.new(
      params
        .require(:product)
        .permit(:category_id, :sub_category_id, :product_url)
    ).fetch_from_url
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to existing_products_path(product: @product.slug)
    else
      render :new
    end
  end

  def search
    keyword = params[:keyword].strip
    @products = Product.where('title LIKE :keyword OR description LIKE :keyword', keyword: "%#{keyword}%")
    @products = @products.where(sub_category_id: params[:sub_category_id]) if params[:sub_category_id].present?
  end

  def existing
    @product = Product.friendly.find(params[:product])
    if @product.present?
      @products = Product.where(sub_category_id: @product.sub_category_id).order('created_at DESC');
      @deal = Deal.new
      @deal.product_deals.build
    end
  end

  def deal
  
  end  

  private

  def product_params
    params.require(:product).permit(
      :product_url, :title, :category_id, :sub_category_id,
      :price_amount, :unit, :description,
      product_images_attributes: %i[img image_url]
    )
  end
end

app/views/products/_deal_product.html.erb
<% if deal_products.present? 
  deal_products.each do |deal_product| 
    product = deal_product.product
    deal = deal_product.deal
    timer = remaining_time(deal.expired_at)
    # discounts = deal.discounts
%>
  <div class="small-6 medium-6 large-3  columns">
    <a href="<%= deal_product_path(1) %>">
      <div class="single_products">
        <div class="Products_img">
          <%= image_tag product.primary_image, alt: 'shoe-big' %>
        </div>
        <div class="product_price">
          <h3><%= display_price(product.standard_price) %></h3>
          <p>8% OFF</p>
        </div>


        <div class="Products_title">
          <h3><%= display_truncate_content(strip_tags(product.description), 40) %><br/>
          <a href="#" class="name"><%= product.title %></a></h3>
          
          <div class="sub_fil">
            <div class="category_name_filter">
              <span class="category_name"><a href="javascript:void(0)" data-open="product_discount_table">DISCOUNT TABLE</a></span>
              <span class="category_name"><a href="#">10 COMMITS</a></span>
              <span class="category_name"><a href="#">MN</a></span>
            </div>
          </div>

          <div class="commit_area">
            <div class="commit_bar">
              <span class="active_bar full_bar"></span>
            </div>
            <div class="commit_count">
              <button class="commits_btn" type="button">COMMIT</button>
            </div>
          </div>
        </div>

        <div class="pro_timmer no-padding">
          <div class="time">
            <div class="time-box">
              <span><em><%= timer[:day]%></em>days</span>
              <span><em><%= timer[:hour]%></em>hours</span>
              <span><em><%= timer[:minute]%></em>min</span>
              <span><em><%= timer[:second]%></em>sec</span>
            </div>
          </div>
        </div>

      </div>
    </a>
  </div>
<% end
else %>
  <div class="small-12 medium-12 large-6">No Deal found !</div>
<% end %>

app/views/products/_explore_product.html.haml
- products.each do |product|
  .medium-3.columns
    %a{:href => "#{product_path(product)}"}
      .single_products
        .Products_img
          = image_tag 'shoe.jpg', class: 'img-response', style: 'width: 150px; height: 150px;'
        .product_price
          %p 78% OFF
        .Products_title
          %h3
            = product.title
            %br/
            %a.name{:href => "#"}
          .sub_fil
            .category_name_filter
              %span.category_name
                %a{:href => "#"} Hopkins
              %span.category_name
                %a{:href => "#"} Minnesota
              %span.category_name
                %a{:href => "#"}
                  %i.fa.fa-link
          .commit_area
            .commit_count
              %p
                %span.commit_num= product.requests.length
                REQUESTS
              %p
                %span.commit_num= product.requests.map(&:quantity).sum
                UNITS
            .Request_btn
              = link_to request_add_path(product.id), remote: true do
                %button.commits_btn{ type: "button" } REQUEST
              %button.commits_btn{"data-open" => "product_pop_dic_sell", :type => "button"} SELL
        .pro_timmer.no-padding-2
          %h3.std_price
            %span $180.56
            Standard Price
          .midle_bar
          %h3
            %span $150.56
            Requested Price
  

app/views/products/_request_product.html.haml
- requests.each do |request|
  .columns.medium-6.large-6
    - product = request.product
    = link_to product, class: 'hover_btn' do
      .single_request
        .row
          .columns.medium-3
            .res_product_img
              = image_tag product.primary_image, alt: 'alpha'
          .columns.medium-9
            .Req_details.Products_title
              %h3
                = product.title
                %br/
                %a.name{:href => "#"} – by Rapture
              .widget_req
                .seller_details
                  %a{:href => "#"} Men's Apparel
                  %a{:href => "#"} T-Shirt
                  %span.category_name
                    %a{:href => "#"}
                      %i.fa.fa-link
              .price_req
                %p.std_price
                  Standard Price:
                  %span= number_to_currency(product.price_amount)
                %p
                  Requested Price:
                  %span= number_to_currency(request.asked_price)
              .req_btn
                .req_numer
                  %p
                    Requests:
                    %span 50
                .reqest_btns
                  = link_to edit_request_path(request.id), remote: true do
                    %button.re_btn{:type => "button"} edit
                  %button.re_btn{:type => "button"} cancel

app/views/products/create.js.erb
<% if @product.errors.messages.length == 0 %>
  $('.modal-form-wrapper').html("<%=j render 'shared/modal/assign_discount_by_product', products: @products, product: @product, sub_category_id: @product.sub_category_id %>");
  $(document).foundation();
  $('#product_pop_add').foundation('close');
  $('#product_pop_dic_sell').foundation('open');
  $('#product_pop_dic_sell').on('closed.zf.reveal', function(){
    $(this).remove();
  });
<% else %>
  $('.error-wrapper').html("<p class='help-text' style='color: red;'><%= @product.errors.full_messages.join(', ') %></p>");
<% end %>

app/views/products/deal.html.erb
<%= title 'YOVA | Deals' %>
<div class="Products_details_header">
  <div class="row">
    <div class="columns small-12">
      <a href="<%= deals_path %>" class="back_link"><i class="fa fa-angle-double-left" aria-hidden="true"></i> All Deals</a>
      <div class="wideget_list">
        <div class="filter_list">
          <div class="details_title">
            <h2>Spier & Mackay Polo Shirts</h2>
            <a href="#" class="name">by Nike</a>
          </div>
          <a href="#">Men's Apparel</a>
          <a href="#">T-Shirt</a>
          <a href="#"><i class="fa fa-star" ></i> Save</a>
        </div>
        <div class="right_head_details">
          <div class="socail_icon">
            <p>SHARE THIS REQUEST</p>
            <ul>
              <li><a href="#"><i class="fa fa-tags" ></i></a></li>
              <li><a href="#"><i class="fa fa-link"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-reddit-alien"></i></a></li>
            </ul>
          </div>
          <div class="right_head_btns">
            <button class="button" data-open="product_pop_dic_sell">SELL</button>
            <button class="button" data-open="product_pop_dic_sell">Edit </button>
            <button class="button">cancel </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="main_pro_details">

  <div class="row">
    <div class="columns small-9 large-9 medium-9">
      <div class="main_desctibetion">
        <div class="big_img_pre">
          <div class="row">
            <div class="columns">
              <div class="tabs-content imageGallery1" data-tabs-content="example-tabs">
                <div class="tabs-panel is-active" id="panel1">
                  <a  href="<%= image_path('t-shirt.jpg') %>" ><img  src="<%= image_path('t-shirt.jpg') %>" alt="t-shirt"></a>
                </div>
                <div class="tabs-panel" id="panel2">
                  <a href="<%= image_path('img-2.jpg') %>" ><img  src="<%= image_path('img-2.jpg') %>" alt="t-shirt"></a>
                </div>
                <div class="tabs-panel" id="panel3">
                  <a  href="<%= image_path('t-shirt.jpg') %>" ><img  src="<%= image_path('t-shirt.jpg') %>" alt="t-shirt"></a>
                </div>
                <div class="tabs-panel" id="panel4">
                  <a  href="<%= image_path('img-2.jpg') %>" ><img  src="<%= image_path('img-2.jpg') %>" alt="t-shirt"></a>
                </div>
                <div class="tabs-panel" id="panel5">
                  <a  href="<%= image_path('t-shirt.jpg') %>" ><img  src="<%= image_path('t-shirt.jpg') %>" alt="t-shirt"></a>
                </div>
                <div class="tabs-panel" id="panel6">
                  <a  href="<%= image_path('img-2.jpg') %>" ><img  src="<%= image_path('img-2.jpg') %>" alt="t-shirt"></a>
                </div>
              </div>

              <ul class="tabs" data-tabs id="example-tabs">
                <li class="tabs-title is-active"><a href="#panel1" aria-selected="true"><img src="<%= image_path('small-pre/1.jpg') %>" alt="t-shirt"></a></a></li>
                <li class="tabs-title"><a href="#panel2"><img src="<%= image_path('small-pre/2.jpg') %>" alt="t-shirt"></a></li>
                <li class="tabs-title"><a href="#panel3"><img src="<%= image_path('small-pre/1.jpg') %>" alt="t-shirt"></a></li>
                <li class="tabs-title"><a href="#panel4"><img src="<%= image_path('small-pre/2.jpg') %>" alt="t-shirt"></a></li>
                <li class="tabs-title"><a href="#panel5"><img src="<%= image_path('small-pre/1.jpg') %>" alt="t-shirt"></a></li>
                <li class="tabs-title"><a href="#panel6"><img src="<%= image_path('small-pre/2.jpg') %>" alt="t-shirt"></a></li>
              </ul>
            </div>
          </div>
        </div>

        <div class="filter_del_locker">
          <div class="owl-carousel owl-theme" id="buyer_table">
            <div class="items items_active">
              <p><span class="ser_num">Buy 1-15</span> <br/><span class="co_class">$43.20</span>/ea</p>
            </div>
            <div class="items">
              <p><span class="ser_num">Buy 16 – 20</span> <br/><span class="co_class">$43.20</span>/ea</p>
            </div>
            <div class="items">
              <p><span class="ser_num">Buy 21 - 35</span> <br/><span class="co_class">$43.20</span>/ea</p>
            </div>

            <div class="items">
              <p><span class="ser_num">Buy 36 – 45</span> <br/><span class="co_class">$43.20</span>/ea</p>
            </div>

            <div class="items">
              <p><span class="ser_num">Buy 46 – 55</span> <br/><span class="co_class">$43.20</span>/ea</p>
            </div>
            <div class="items">
              <p><span class="ser_num">Buy 1-15</span> <br/><span class="co_class">$43.20</span>/ea</p>
            </div>

          </div>
        </div>



        <div class="text_details">
          <h3>The Power of Snail Extract</h3>

          <p>From Korean skincare company Mizon, these products are cult favorites for good reason. The All-in-One Snail Repair
            Cream does it all—from fading hyperpigmentation and acne scarring, to minimizing pores and blackheads, to fighting
            fine lines and other signs of aging. It’s formulated with 92-percent snail filtrate, different plant extracts,
            and a number of antioxidant-rich ingredients.</p>

          <p>Apply it as the final step of your skincare routine in the morning, at night, or both. Made with 74-percent snail
            extra, the Snail Recovery Gel Cream’s lightweight formula provides serious hydration without leaving behind a
            greasy sheen. Apply it over your face and neck as part of your daily routine, double up and use it as a sleeping
            mask, or dab on a small amount wherever you need to soothe inflammation.</p>



          <h3>About Mizon</h3>

          <p>At Mizon, Korea’s leading beauty researchers and scientists come together to make incredible products accessible
            to everyone. Each product features generous portions of the best, most highly regarded active ingredients to
            make sure your skin gets the maximum benefits.</p>

          <h3>Included</h3>

          <ul>
            <li>All-in-One Snail Repair Cream (75ml pot)</li>
            <li>All-in-One Mizon Snail Recovery Gel Cream (45ml tube)</li>
          </ul>

          <h3>Ingredients</h3>

          <p>Mizon All-in-One Snail Repair Cream: Snail Secretion Filtrate, Cetearyl Olivate, Sorbitan Olivate, Cetearyl Alcohol,
            Stearic Acid, Glyceryl Stearate, Hydrogenate Vegetable Oil, Dimethicone, Triethanolamine, Carbomer, Butylene
            Glycol, PED/PPG-17/6 Copolymer, Polyacrylate-13, Polyisobutene, Polysorbate 20, Sodium Polyacrylate, Caprylyl
            Glycol, Ethylhexylglycerin, Tropolone, Adenosine, Sodium Hyaluronate, Portulaca Oleracea Extract, Betula Platyphylla
            Japonica Juice, Amica Montana Flower Extract, Artemisia Absinthium Extract, Achillea Millefolium Extract, Gentiana
            Lutea Root Extract, Alcohol, Camellia Sinensis Leaf Extract, Centella Asiatica Extract, Copper Tripeptide-1,
            Human Oligopeptide-1, Propylene Glycol, Rubus Idaeus (Rasberry) Fruit Extract, Beta-Glucan, Palmitoyl Pentapeptide-4,
            Disodium EDTA</p>

          <p>Mizon Snail Recovery Gel Cream: Snail Secretion Filtrate, Butylene Glycol, Cyclopentasiloxane, Glycerin, Bis-Peg-18
            Methyl Ether Dimethyl Silane, Polysorbate 20, Sodium Hyaluronate, Carbomer, Glycosyl Trehalose, Hydrogenated
            Starch Hydrolysate, Triethanolamine, Dimethicone/Vinyl Dimethicone Crosspolymer, Dimethicone, Hydroxyethylcellulose,
            Caprylyl Glycol, Ethylhexylglycerin, Sodium Polyacrylate, Centella Asiatica Extract, Portulaca Oleracea Extract,
            Camellias Sinensis Leaf Extract, Nelumbo Nucifera Flower Extract, Betula Platylphylla Japonica Juice, Tropolone,
            Copper Tripeptide-1, Allantoin, Panthenol, Olea Europaea (Olive) Fruit Oil, Helianthus Annuus (Sunflower) Seed
            Oil, Palmitoyl Pentapeptide-4, Adenosine, Disodium EDTA</p>

          <h3>Shipping</h3>
          <p>All orders will be shipped by Massdrop.</p>

          <p>Estimated ship date is Aug 7, 2017 PT.</p>

          <p>After the drop ends, payment will be collected. To deliver the best value to the group the request will then be
            submitted to the vendor up front, making all sales final. Be sure to check the discussion page for updates.</p>
        </div>
      </div>


    </div>

    <div class="columns small-3 large-3 medium-3">
      <div class="side_bar" id='product-sidebar'>
        <div class="price_section">
          <div class="discount_price">
            <h3>$17.99 <span>2% OFF</span></h3>
            <p>Standard Price:
              <del>$19.99</del>
            </p>
          </div>
          <div class="offer_left">
            <p>Units Aggregated :<span> 300</span> </p>
            <p>Requests: <span>50</span></p>
          </div>


          <div class="time_left">
            <div class="pro_timmer no-padding">
              <div class="time">
                <div class="time-box">
                  <span><em>01</em>days</span>
                  <span><em>00</em>hours</span>
                  <span><em>12</em>min</span>
                  <span><em>52</em>sec</span>
                </div>
              </div>
            </div>
          </div>

          <a class="join_btn" href="#">COMMIT &nbsp;&nbsp;
              <i class="fa fa-info-circle has-tip top" data-tooltip aria-haspopup="true" data-disable-hover="false" tabindex="2" title="From Korean skincare company Mizon, these products are cult"></i>
              </a>

        </div>
      </div>
    </div>
  </div>




  <div class="row product_margin_top color_a">
    <div class="columns medium-12">
      <div class="other_title">
        <h3> Other Deals</h3>
      </div>
    </div>
    <%#= render 'products/deal_product', num_items: 4 %>
  </div>



  <div class="row">
    <div class="more_deals">
      <a href="<%= deals_path %>">See All Deals</a>
    </div>
  </div>
</div>
<%#= render 'shared/modal/assign_discount_by_product' %>

app/views/products/existing.html.erb
<%= title 'Account | Assign Discounts' %>
<div class="main_product_area">

  <div class="discount_asign_page">
    <div class="product_discount_title">
      <h3>Assing the Discounts</h3>
      <p>Assign discounts to products or category</p>
    </div>
    <div class="product_discount" data-open="product_pop_dic_sell">
      <%= image_tag 'discount-pro.png', alt: 'discount-pro' %>
      <h3> Products Discount</h3>
    </div>
    <div class="product_discount" data-open="product_pop_dic_category">
      <%= image_tag 'discount-ca.png', alt: 'discount-ca' %>
      <h3> Products Category Discount</h3>
    </div>
  </div>
  <div class='modal-form-wrapper'></div>
  <% if @product.present? %>
    <%= render 'shared/modal/assign_discount_by_product', products: @products, product: @product, sub_category_id: @product.sub_category_id %>
      <script>
        $(document).foundation();
        $('#product_pop_dic_sell').foundation('open'); 
      </script>  
  <% else %>
    <%= render 'shared/modal/assign_discount_by_product' %>
  <% end %>
  <%= render 'shared/modal/assign_discount_by_product_category' %>
</div>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

app/views/products/fetch.js.erb
<% if @product.errors.messages.length == 0 %>
  $('.modal-form-wrapper').html("<%=j render 'products/new/modal_form', product: @product, subcategories: @product.category.childrens.map { |c| [c.name, c.id] } %>");
  $(document).foundation();
  $('#product_pop_add').foundation('close');
  $('#product_pop_add_inner').foundation('open');
  $('#product_pop_add_inner').on('closed.zf.reveal', function(){
    $(this).remove();
  });
<% else %>
  $('.error-wrapper').html("<p class='help-text' style='color: red;'><%= @product.errors.full_messages.join(', ') %></p>");
<% end %>

app/views/products/new.html.haml
= title 'YOVA | DEALS'
.main_product_area
  .row
    .columns.medium-6.medium-offset-3
      .add_product_box
        %h3 Add New Product
        %hr
        .add_product_box_inner
          %h3 Choose a category to assign your product to
          = select_tag :category_id, options_from_collection_for_select(Category.parents_only, 'id', 'name'), {prompt: 'Choose a Category',  class: 'form__selectmenu', data: { action: 'select-category', category_url: categories_path(format: :json) } }
          .category-id-errors-wrapper
          %br
          %br
          %h3 Choose a subcategory
          = select_tag :sub_category_id, [], { class: 'form__selectmenu', data: { action: 'select-subcategory' } }
          .sub-category-id-errors-wrapper
          %br
          %br
          %span#open-product_pop_add.add_btn_pro.reveal-open
            = image_tag 'add-plus.png', alt: 'add-plus'
            %p ADD PRODUCT

.modal-form-wrapper
  - if @product.errors.present?
    = render 'products/new/modal_form', product: @product 
    :javascript
      $(document).foundation();
      $('#product_pop_add_inner').foundation('open');
  - else
    = render 'products/new/modal_product_url', product: @product

app/views/products/search.js.erb
$('#edit-item').html("<%=j render 'shared/modal/product_list', products: @products %>");
  